### ISSUE TITLE
deps parsing in setup.py

### ISSUE THREAD

**Issue by Chris2048** [ronlut/flask-inflate#1]
I get the error:

      IOError: [Errno 2] No such file or directory: 'requirements.txt'

when trying to install this package via pip; Is the requirements file making it into Flask-Inflate-0.2.tar.gz ?

**Comment by ronlut** [comment]
Hi @Chris2048, thanks for the heads up.
Indeed it was missing from the source gzip.
Fixed, please see [v0.3](https://pypi.org/project/Flask-Inflate/0.3/). Let me know if something is still wrong :)
